apiVersion: v1alpha
kind: espresso
defaults: {}
showConsoleLog: false
sauce:
  region: eu-central-1
  concurrency: 10
espresso:
  app: Flipkart_Online_Shopping_App_v7.65.apk
  testApp: Flipkart_Online_Shopping_App_v7.65.apk
suites:
- name: espresso - Samsung .* - Android GoogleAPI Emulator
  devices:
  - name: Samsung .*
  emulators:
  - name: Android GoogleAPI Emulator
    platformVersions:
    - "13.0"
artifacts:
  download:
    match:
    - '*'
    when: always
    directory: artifacts
